### ISSUE TITLE
Improvement: Add twitter:creator as variable in project yml

### ISSUE THREAD

**Issue by vdeville** [Skyost/SkyDocs#1]
Hello,

Can you add twitter:creator as variable for project ?

thanks

**Comment by Skyost** [comment]
Hey,

You're free to put custom variables in _project.yml_. For instance, let's create a `custom_variable` variable ([image](http://i.imgur.com/50HtSs1.png)).      
You can load it with `project.getField("custom_variable")` ([image](http://i.imgur.com/rPvlP78.png)).     
Which will give you [this](http://i.imgur.com/rW9HvA4.png) :wink:

Feel free to edit _project.yml_ as you want, same for the default theme.

**Comment by vdeville** [comment]
Thanks
