### ISSUE TITLE
Not possible to scroll the page!

### ISSUE THREAD

**Issue by vPrapo** [Skyost/SkyDocs#11]
Not possible to scroll any page in your website
Tried Chrome and Firefox
in Chrome Mobile I can scroll it works fine
but not possible when I request desktop mode

**Comment by Skyost** [comment]
Hey,

It seems to be a browser change, I'm going to investigate.

**Comment by vPrapo** [comment]
Kindly please apply the changes in
projects.skyost.eu
Thank you

**Comment by Skyost** [comment]
Done :wink:
