### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by haznit** [Skyost/SkyDocs#12]
Here is my request : Hello, does skydocs support several users for collaboration purposes?

**Comment by Skyost** [comment]
Hello,

In fact, SkyDocs is not a platform on where you can create and edit your docs; it's only a tool that allows to build documentations efficiently thanks to (including but not limited to) markdown.

So yes, if you want several users to be able to edit your docs, that's possible !

**Comment by haznit** [comment]
Hi,

Thanks for the reply.
I understand it's not a platform that will host our documentation files.
Those will be hosted on a standalone server. But if skydocs is installed on
that server will it allow me to make documents and save them locally on
that server?
Also by several users, I meant several different users who would have their
own environment et documents and who would not be able to interfere with
each other.

Regards,
Hazni Talay

Op wo 27 mrt. 2019 om 22:49 schreef Hugo Delaunay <notifications@github.com

**Comment by Skyost** [comment]
Yes it is possible :wink:
