### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vdeville** [Skyost/SkyDocs#2]
Hello,

When i use built-in server specials chars do not display and replace with "?". No problem when use build command.

Thanks

**Comment by Skyost** [comment]
Can you please provide me an example of those special chars ? Where did you put them (in MarkDown / in HTML / in theme) ?

**Comment by vdeville** [comment]
In markdown é

**Comment by Skyost** [comment]
It's strange as I get it [working perfectly](http://i.imgur.com/PKpybxR.png). Did you have enabled UTF-8 encoding in your MarkDown editor ?

**Comment by vdeville** [comment]
Yes

**Comment by Skyost** [comment]
Can you please provide me the MarkDown file in question ?
