### ISSUE TITLE
Using LaTex

### ISSUE THREAD

**Issue by vanaur** [Skyost/SkyDocs#22]
Hello,
Is there a way to support LaTex code?
For example, in a Markdown file where we would like to add some mathematical context, write `$someMath$` and have a visual that supports this feature?
A simple example: `$\frac{x}{y}$` should be displayed as ![df](https://user-images.githubusercontent.com/28791317/61134732-872c1500-a4c0-11e9-8548-d7877de11f50.PNG), but apparently SkyDocs doesn't support this feature yet, or should we use a third-party tool?

**Comment by Skyost** [comment]
Sure ! Just edit the default theme and add a dependency to [MathJax](https://www.mathjax.org) or [KaTeX](https://katex.org).

**Comment by vanaur** [comment]
Great, it works fine, thank you.
I noticed that with MathJax and inline math, the proposed form `\(LaTex\)` is later built in HTML in the form `(LaTex)`, to fix this problem, so you have to write originally, in the Markdown file, this : `\\(LaTex\\)`.

**Comment by Skyost** [comment]
Yes or you can use the [raw tag](http://jtwig.org/documentation/reference/functions#raw). Another option is to use the following config :

```js

MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [
      ['$','$']
    ]
  },
});
```

Then you can enter your inline math like this `$\delta = b^2 - 4ac$`.
