### ISSUE TITLE
How to re-order page ?

### ISSUE THREAD

**Issue by vdeville** [Skyost/SkyDocs#4]
It's possible to re-order page ? For next and previous button ?

**Comment by Skyost** [comment]
You have two options :

- You can put `default_order_alphabetical: true` in `project.yml` which will result in an alphabetical ordering.
- In MarkDown files header, you may already have two keys `title` and `language`. You can put two other keys `previous` and `next`, therefore you will be able to use `page.getPrevious()` and `page.getNext()`. For example [this header](http://i.imgur.com/OVmYu0r.png) will give you [this result](http://i.imgur.com/04M2XG9.png).

**Comment by vdeville** [comment]
Nice, thanks
