### ISSUE TITLE
Improve bloc path

### ISSUE THREAD

**Issue by vdeville** [Skyost/SkyDocs#5]
After long time to upload website on gh-pages github, it's not user friendly big problem with path / folders, sub folders.

Can you add base url variable for the project ? 

Solve hars path in theme is not good solution for long time.

**Comment by Skyost** [comment]
This has been fixed in https://github.com/Skyost/SkyDocs/commit/1b18a1bae0081a18c1e83573d9c2b6eef64bddd8 and is therefore available in the [latest dev builds](https://skyost.github.io/SkyDocs/en/documentation.html#development-builds) via the method `page.getRootRelativeURL()` :wink:
